spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          product-service:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 3000
            request-interceptors:
              - com.example.order.interceptor.XTokenRequestInterceptor
feign:
  sentinel:
    enabled: true
