spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true

  application:
    name: product-service

server:
  port: 9000
